server:
  port: 8100
spring:
  application:
    name: ms-notification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      user: admin
      password: admin
      uri: mongodb://admin:admin@localhost/db_notify?authSource=admin